### PR TITLE
Allows dummy objective expressions (#7)

### PR DESCRIPTION
**Pull request by amarvin**

### CODE REVIEW

**Comment by whart222** [comment]
Can you provide a test case that illustrates the use of this?  I'm not sure what a motivating example would be.

The appveyor test failures appear unrelated to this functionality.  I'm not sure, but they may have been failing for a while.

**Comment by amarvin** [comment]
Good idea @whart222, I just added an example with a dummy objective function. If the objective function is a constant (in this case a float of 1.0), the check of this expression fails when trying to read the is_relational attribute that doesn't exist in the float object.

**Comment by amarvin** [comment]
All these checks should pass, once #10 is merged.

**Comment by amarvin** [comment]
Can this update and new test be merged?

**Comment by whart222** [comment]
The test failures appear un-related, so I'm approving this PR.

**Pull request merged**
